"""Quantitative evidence that closes inside this repo (no external claims).

For every synthetic preset:
  - crowding (mm) and which strategy the ladder settles on, with / without extraction allowed (the extraction column
    prescribes the first premolars 5·12 as an experiment: the app never picks teeth itself, #56)
  - how many rule violations the validator caught in the strategies it rejected on the way
  - a naive baseline: "align without gaining space" (what a plan looks like if you skip strategy + validation)
  - wall time of the whole ladder

Writes a markdown table. Run: `cualign bench` or `python bench/bench.py`.
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cualign.core import Case, limits as L, planner  # noqa: E402
from cualign.core.constraints import Constraints  # noqa: E402

PRESETS = ["aligned", "mild", "moderate", "severe", "extraction"]
BENCH_EXTRACTION = (5, 12)   # the prescription the extraction column assumes


def ladder(case: Case, allowed, stage_cap=None, order="simultaneous"):
    tried = []
    for s in allowed:
        target, info = planner.propose_target(case, s, extraction=BENCH_EXTRACTION if s == "extraction" else ())
        stages, sinfo = planner.plan_stages(case, target, order=order)
        viol = planner.validate(case, stages, stage_cap=stage_cap, space_deficit_mm=info["space_deficit_mm"],
                                constraints=Constraints(extraction=BENCH_EXTRACTION if s == "extraction" else ()))
        tried.append((s, sinfo["n_stages"], sinfo["months"], viol))
        if not viol:
            break
    return tried


def naive_baseline(case: Case):
    """No space-gaining strategy: place crowns in contact on the current arch and stage linearly."""
    target, info = planner.propose_target(case, "expansion")   # reuse geometry, then undo the gain bookkeeping
    # a naive planner would not expand; emulate by declaring gain 0 -> deficit = crowding
    stages, sinfo = planner.plan_stages(case, target)
    viol = planner.validate(case, stages, space_deficit_mm=info["crowding_mm"])
    return sinfo["n_stages"], viol


def main(out: str = "bench/results.md") -> str:
    rows = []
    for name in PRESETS:
        t0 = time.time()
        case = Case.synthetic(name)
        crowd = planner.crowding_mm(case)
        with_ext = ladder(case, L.STRATEGIES)
        no_ext = ladder(case, [s for s in L.STRATEGIES if s != "extraction"])
        n_naive, v_naive = naive_baseline(case)
        dt = time.time() - t0
        def fmt(tr):
            s, n, m, v = tr[-1]
            caught = sum(len(t[3]) for t in tr[:-1]) + (len(v) if v else 0)
            return (f"{s} · {n}장 · {m}개월" if not v else f"실패({planner.summarize(v)})"), len(tr), caught
        a, na, ca = fmt(with_ext)
        b, nb, cb = fmt(no_ext)
        rows.append((name, crowd, a, na, ca, b, nb, cb, n_naive, len(v_naive), dt))
    lines = ["# cuAlign bench — synthetic presets (no patient data)", "",
             f"Generated by `cualign bench`. Limits: {L.MAX_LINEAR_PER_ALIGNER} mm/aligner · IPR {L.IPR_PER_SURFACE} mm/surface · "
             f"expansion ≤ {L.MAX_EXPANSION_PER_SIDE} mm/side · wear {L.WEAR_DAYS} d. Stage counts assume translation-only, simultaneous staging.", "",
             "| preset | crowding (mm) | ladder result (extraction allowed) | strategies tried | violations caught | ladder result (no extraction) | tried | caught | naive plan stages | naive violations | time (s) |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append("| " + " | ".join(str(x) if not isinstance(x, float) else f"{x:.1f}" for x in r) + " |")
    lines += ["", "Reading: 'violations caught' = rule violations the validator found in rejected strategies before settling — "
              "each one is a plan a naive pipeline would have shipped. 'naive' = align in place without gaining space and without validation; "
              "its violation count is what the dentist would otherwise catch by eye.", ""]
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    return out


if __name__ == "__main__":
    main()
